# Generated by Django 4.2 on 2023-04-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='user_question',
            new_name='user_input',
        ),
    ]
